coverage:
  status:
    patch:
      default:
        target: '90'
    project:
      default:
        target: '90'
comment:
  layout: "header, diff"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  branches: null
  flags: null
  paths: null
