@deprecate BullGraph() bull_graph()
@deprecate ChvatalGraph() chvatal_graph()
@deprecate CubicalGraph() cubical_graph()
@deprecate DesarguesGraph() desargues_graph()
@deprecate DiamondGraph() diamond_graph()
@deprecate DodecahedralGraph() dodecahedral_graph()
@deprecate FruchtGraph() frucht_graph()
@deprecate HeawoodGraph() heawood_graph()
@deprecate HouseGraph() house_graph()
@deprecate HouseXGraph() house_x_graph()
@deprecate IcosahedralGraph() icosahedral_graph()
@deprecate KarateGraph() karate_graph()
@deprecate KrackhardtKiteGraph() krackhardt_kite_graph()
@deprecate MoebiusKantorGraph() moebius_kantor_graph()
@deprecate OctahedralGraph() octahedral_graph()
@deprecate PappusGraph() pappus_graph()
@deprecate PetersenGraph() petersen_graph()
@deprecate SedgewickMazeGraph() sedgewick_maze_graph()
@deprecate TetrahedralGraph() tetrahedral_graph()
@deprecate TruncatedCubeGraph() truncated_cube_graph()
@deprecate TruncatedTetrahedronGraph() truncated_tetrahedron_graph()
@deprecate TruncatedTetrahedronDiGraph() truncated_tetrahedron_digraph()
@deprecate TutteGraph() tutte_graph()
@deprecate CompleteGraph(n) complete_graph(n)
@deprecate CompleteBipartiteGraph(n1, n2) complete_bipartite_graph(n1, n2)
@deprecate CompleteMultipartiteGraph(partitions) complete_multipartite_graph(partitions)
@deprecate TuranGraph(n, r) turan_graph(n, r)
@deprecate CompleteDiGraph(n) complete_digraph(n)
@deprecate StarGraph(n) star_graph(n)
@deprecate StarDigraph(n) star_digraph(n)
@deprecate PathGraph(n) path_graph(n)
@deprecate PathDiGraph(n) path_digraph(n)
@deprecate CycleGraph(n) cycle_graph(n)
@deprecate CycleDiGraph(n) cycle_digraph(n)
@deprecate WheelGraph(n) wheel_graph(n)
@deprecate WheelDiGraph(n) wheel_digraph(n)
@deprecate Grid(dims; periodic=false) grid(dims; periodic=false)
@deprecate BinaryTree(k) binary_tree(k)
@deprecate Doublebinary_tree(k) double_binary_tree(k)
@deprecate RoachGraph(k) roach_graph(k)
@deprecate CliqueGraph(k, n) clique_graph(k, n)
@deprecate LadderGraph(n) ladder_graph(n)
@deprecate Circularladder_graph(n) circular_ladder_graph(n)
@deprecate BarbellGraph(n1, n2) barbell_graph(n1, n2)
@deprecate LollipopGraph(n1, n2) lollipop_graph(n1, n2)
